### ISSUE TITLE
Data retention period limit unclear

### ISSUE THREAD

**Issue by hillaryl** [cds-snc/policy-politique#6]
In the *[*CDS Web Analytics Policy Checklist**](https://cds-snc.github.io/policy-politique/en/2020/cds-web-analytics-policy-checklist/) it says:

> Data retention period is set for max 6 months, or the shortest option available
> 
> Google Analytics:
> 
> Set data retention period at 14 months. Google Analytics doesn't allow a retention period shorter than this, and most of the data collected by GA is exempt from the 6 month retention limit because it's aggregated.

Does this mean that the data retention period can be set to 14 months if the anonymization setting described earlier is enabled?

**Comment by lchski** [comment]
Closing per discussion—advice in the checklist stands, 14 months works!
